### ISSUE TITLE
Transfer saves to official session : 转换存档到至官方 Thread 会话

### ISSUE THREAD

**Issue by Chinese-Cyq20100313** [bigemon/ChatGPT-ToolBox#1]
Currently, the OpenAI have an official way to save your session. May you find a way to transfer your coversation_id to a OpenAI thread_id?
一不小心就写了点英文，ChatGPT练习英文对话太好了（
现在OpenAI有了官方的会话存储Thread，能不能转换你的conversation_id到官方的thread_id。不然每次还要导入...而且还会丢失...

**Comment by bigemon** [comment]
如果之前存档保存的是自己的会话。
则会话会在导出账号的位置继续存在。

目前官方的会话链接类似于：https://chat.openai.com/chat/{coversation_id}
如果会话太多一时找不到，可以将你的存档找一个在线base64解码服务进行解码，然后将上述链接里的{coversation_id}替换成存档里的coversation_id即可。
<img width="825" alt="image" src="https://user-images.githubusercontent.com/3683548/208829883-89d83440-02dc-4d19-a67e-b6c4462934cf.png">


需要注意的是：
1.如果使用过官方的那个清空会话或者删除会话，并且删除了这个Thread，那么可能就找不到了
2.如果之前使用过早期版本的跨账号Thread分享，并且是由别的账号导出，
则应该到那个导出账号找Thread。因为之前的跨账号分享本质上是把那个账号的Thread数据和鉴权token都导出出来。所以官方的这个会话上下文重建之后还是在原账号。


鉴于官方存档和当前的第三方存档管理器功能重复。
迟一点将会把库里的存档功能暂时移除。
至于跨账号存档分享，如果之后CGPT服务稳定了不会经常掉token，会再找个时机加回来。

**Comment by Chinese-Cyq20100313** [comment]
> 如果之前存档保存的是自己的会话。 则会话会在导出账号的位置继续存在。
> 
> 目前官方的会话链接类似于：[https://chat.openai.com/chat/{coversation_id}](https://chat.openai.com/chat/%7Bcoversation_id%7D) 如果会话太多一时找不到，可以将你的存档找一个在线base64解码服务进行解码，然后将上述链接里的{coversation_id}替换成存档里的coversation_id即可。 <img alt="image" width="825" src="https://user-images.githubusercontent.com/3683548/208829883-89d83440-02dc-4d19-a67e-b6c4462934cf.png">
> 
> 需要注意的是： 1.如果使用过官方的那个清空会话或者删除会话，并且删除了这个Thread，那么可能就找不到了 2.如果之前使用过早期版本的跨账号Thread分享，并且是由别的账号导出， 则应该到那个导出账号找Thread。因为之前的跨账号分享本质上是把那个账号的Thread数据和鉴权token都导出出来。所以官方的这个会话上下文重建之后还是在原账号。
> 
> 鉴于官方存档和当前的第三方存档管理器功能重复。 迟一点将会把库里的存档功能暂时移除。 至于跨账号存档分享，如果之后CGPT服务稳定了不会经常掉token，会再找个时机加回来。

我之前也扒过代码，知道是Base64，然后我是在手机上用的，然后我但是也没多想，直接用alert把localStorage中的数据输出，然后一个一个id试，我也看到[https://chat.openai.com/chat/xxxxxxxx-xxxx-xxxx-xxxxxxxx](https://chat.openai.com/chat/%7Bcoversation_id%7D)了，然后我直接访问我好像也试过了，没用，然后我就往XHR中断点，然后修改请求的url换conversation_id，然后还是不行，我现在也退出了，存档也失效了。

**Comment by Chinese-Cyq20100313** [comment]
现在我开直接redirect到 /chat

**Comment by GTMssj** [comment]
也就是说存档功能本身并不是保存之前的对话内容，而是token吗？
请问可以保留导出存档的功能吗？这样创建副本比较方便

**Comment by Chinese-Cyq20100313** [comment]
> 也就是说存档功能本身并不是保存之前的对话内容，而是token吗？ 请问可以保留导出存档的功能吗？这样创建副本比较方便



> 也就是说存档功能本身并不是保存之前的对话内容，而是token吗？ 请问可以保留导出存档的功能吗？这样创建副本比较方便

这个原理就是重写了fetch，你去问ChatGPT重写fetch并获取conversation_id
或者直接fork把最近的一次commit撤销了，自己改一下。
