### ISSUE TITLE
发布请求

### ISSUE THREAD

**Issue by Haorwen** [bigemon/ChatGPT-ToolBox#10]
你好作者，我编写了一个自动加载chatgpt工具箱的脚本，地址：https://greasyfork.org/zh-CN/scripts/459199-chatgpt-toolbox
但因为弹窗会阻断cf的认证，所以我在代码中禁用了alert，我在脚本简介标明了你的gh仓库，我可以继续将他发布在greasyfork吗qwq

**Comment by bigemon** [comment]
> 你好作者，我编写了一个自动加载chatgpt工具箱的脚本，地址：https://greasyfork.org/zh-CN/scripts/459199-chatgpt-toolbox 但因为弹窗会阻断cf的认证，所以我在代码中禁用了alert，我在脚本简介标明了你的gh仓库，我可以继续将他发布在greasyfork吗qwq

欢迎，请随意使用。

PS: 如果油猴没有限制Local Storage的读写的话，或许我们可以通过构建一个本地缓存，从而避免网络加载的延迟。
如果需要任何帮助请告诉我。

**Comment by Miller-du** [comment]
您也可以看一下我之前发布的您的脚本，一直是同步更新的。地址：https://greasyfork.org/zh-CN/scripts/456901-chatgpt%E5%8A%9F%E8%83%BD%E5%A2%9E%E5%BC%BA 。（油猴不限制 Local Storage）

**Comment by bigemon** [comment]
> 您也可以看一下我之前发布的您的脚本，一直是同步更新的。地址：https://greasyfork.org/zh-CN/scripts/456901-chatgpt%E5%8A%9F%E8%83%BD%E5%A2%9E%E5%BC%BA 。（油猴不限制 Local Storage）

感谢搬运。稍后我将二位greasyfork的地址加入README。

顺便一提：oof标志符重载对于高负载时，登录页的“ChatGPT is at capacity right now” 提示应该也有作用，
建议将login页面也加入 @match 规则（不过可能需要延迟加载以防止某些问题？）。

**Comment by Miller-du** [comment]
> > 您也可以看一下我之前发布的您的脚本，一直是同步更新的。地址：https://greasyfork.org/zh-CN/scripts/456901-chatgpt%E5%8A%9F%E8%83%BD%E5%A2%9E%E5%BC%BA 。（油猴不限制 Local Storage）
> 
> 感谢搬运。稍后我将二位greasyfork的地址加入README。
> 
> 顺便一提：oof标志符重载对于高负载时，登录页的“ChatGPT is at capacity right now” 提示应该也有作用， 建议将login页面也加入 @match 规则（不过可能需要延迟加载以防止某些问题？）。

感谢。我设置的运行时刻是 `document-idie` ，是否还需要延迟？目前没有找到好的测试方法。

**Comment by bigemon** [comment]
> > > 您也可以看一下我之前发布的您的脚本，一直是同步更新的。地址：https://greasyfork.org/zh-CN/scripts/456901-chatgpt%E5%8A%9F%E8%83%BD%E5%A2%9E%E5%BC%BA 。（油猴不限制 Local Storage）
> > 
> > 
> > 感谢搬运。稍后我将二位greasyfork的地址加入README。
> > 顺便一提：oof标志符重载对于高负载时，登录页的“ChatGPT is at capacity right now” 提示应该也有作用， 建议将login页面也加入 @match 规则（不过可能需要延迟加载以防止某些问题？）。
> 
> 感谢。我设置的运行时刻是 `document-idie` ，是否还需要延迟？目前没有找到好的测试方法。

测试了一下，如@Haorwen所说，在cloudflare的token过期时，oof标志重载将会重写页面，有可能导致无法正常跳转。
不过，遇到这个问题的时候，重新刷新一下就好了。并不影响使用。
回头我让cgpt生成的时候，先检查一下oof标志再覆盖。应该可以避免这种情况的出现。

**Comment by Miller-du** [comment]
> > > > 您也可以看一下我之前发布的您的脚本，一直是同步更新的。地址：https://greasyfork.org/zh-CN/scripts/456901-chatgpt%E5%8A%9F%E8%83%BD%E5%A2%9E%E5%BC%BA 。（油猴不限制 Local Storage）
> > > 
> > > 
> > > 感谢搬运。稍后我将二位greasyfork的地址加入README。
> > > 顺便一提：oof标志符重载对于高负载时，登录页的“ChatGPT is at capacity right now” 提示应该也有作用， 建议将login页面也加入 @match 规则（不过可能需要延迟加载以防止某些问题？）。
> > 
> > 
> > 感谢。我设置的运行时刻是 `document-idie` ，是否还需要延迟？目前没有找到好的测试方法。
> 
> 测试了一下，如@Haorwen所说，在cloudflare的token过期时，oof标志重载将会重写页面，有可能导致无法正常跳转。 不过，遇到这个问题的时候，重新刷新一下就好了。并不影响使用。 回头我让cgpt生成的时候，先检查一下oof标志再覆盖。应该可以避免这种情况的出现。

谢谢，这个问题我明白了，我可以解决一下（因为 `alert` 吧）

**Comment by Haorwen** [comment]
okey，我想我需要做一个监测机制，只有当cf检测完成后才加载脚本，因为在我测试时在cf界面加载脚本后可能导致cf卡死以及多次检测

**Comment by bigemon** [comment]
> > > > > 您也可以看一下我之前发布的您的脚本，一直是同步更新的。地址：https://greasyfork.org/zh-CN/scripts/456901-chatgpt%E5%8A%9F%E8%83%BD%E5%A2%9E%E5%BC%BA 。（油猴不限制 Local Storage）
> > > > 
> > > > 
> > > > 感谢搬运。稍后我将二位greasyfork的地址加入README。
> > > > 顺便一提：oof标志符重载对于高负载时，登录页的“ChatGPT is at capacity right now” 提示应该也有作用， 建议将login页面也加入 @match 规则（不过可能需要延迟加载以防止某些问题？）。
> > > 
> > > 
> > > 感谢。我设置的运行时刻是 `document-idie` ，是否还需要延迟？目前没有找到好的测试方法。
> > 
> > 
> > 测试了一下，如@Haorwen所说，在cloudflare的token过期时，oof标志重载将会重写页面，有可能导致无法正常跳转。 不过，遇到这个问题的时候，重新刷新一下就好了。并不影响使用。 回头我让cgpt生成的时候，先检查一下oof标志再覆盖。应该可以避免这种情况的出现。
> 
> 谢谢，这个问题我明白了，我可以解决一下（因为 `alert` 吧）

事实上，有一些问题（特别是safari的黑屏闪烁）可能是oof标志覆写造成的。
因为cgpt生成的这段代码里并没有检查页面标志，无脑的读入并正则替换有可能会导致页面重复刷新。

如果您有时间的话，可以试试加个检查后，使用匿名模式访问。看看是否正常。
以下是修改后的oof标志覆写：

`// Get the entire page's source code as a string
var pageSource = document.documentElement.outerHTML;

// Check if the page source contains "oof":true
if (pageSource.indexOf('"oof":true') !== -1) {
  // Replace '"oof":true' with '"oof":false'
  pageSource = pageSource.replace(/\"oof\":true/g, '"oof":false');

  // Replace the current page's source code with the modified version
  document.open();
  document.write(pageSource);
  document.close();
}`


*现在想想，或许直接给正在扩容页面加个 “我就是要登录”  按钮会好一些？

**Comment by bigemon** [comment]
> okey，我想我需要做一个监测机制，只有当cf检测完成后才加载脚本，因为在我测试时在cf界面加载脚本后可能导致cf卡死以及多次检测

在最近修复的那个版本，我已经做了一些简单的防重复载入处理。

其它建议：

1. 加上 `// @run-at       document-idle` 指明页面闲置时载入
2. 使用setTimeout设置几十毫秒到一百毫秒的延迟，以防止UserScript用户卡在跳转。
例：
```
window.originalAlert = window.alert;
window.alert = function () {};

setTimeout(function () {
  var xhr = new XMLHttpRequest();
  xhr.open('GET', 'https://ghproxy.com/https://raw.githubusercontent.com/bigemon/ChatGPT-ToolBox/main/toolbox-chrome-bookmark.js', true);
  xhr.onload = function () {
    if (xhr.readyState === 4 && xhr.status === 200) {
      try {
        var response = xhr.responseText;
        (new Function(response))();
            window.alert = window.originalAlert;
      } catch (error) {
        console.error(error);
      }
    }
  };
  xhr.send(null);
}, 100);
```

如果没有遗漏什么的话。
以上的改动应该可以在动态加载时，在大多数chromium内核和macos 的Safari下生效。

**Comment by bigemon** [comment]
> > > > > 您也可以看一下我之前发布的您的脚本，一直是同步更新的。地址：https://greasyfork.org/zh-CN/scripts/456901-chatgpt%E5%8A%9F%E8%83%BD%E5%A2%9E%E5%BC%BA 。（油猴不限制 Local Storage）
> > > > 
> > > > 
> > > > 感谢搬运。稍后我将二位greasyfork的地址加入README。
> > > > 顺便一提：oof标志符重载对于高负载时，登录页的“ChatGPT is at capacity right now” 提示应该也有作用， 建议将login页面也加入 @match 规则（不过可能需要延迟加载以防止某些问题？）。
> > > 
> > > 
> > > 感谢。我设置的运行时刻是 `document-idie` ，是否还需要延迟？目前没有找到好的测试方法。
> > 
> > 
> > 测试了一下，如@Haorwen所说，在cloudflare的token过期时，oof标志重载将会重写页面，有可能导致无法正常跳转。 不过，遇到这个问题的时候，重新刷新一下就好了。并不影响使用。 回头我让cgpt生成的时候，先检查一下oof标志再覆盖。应该可以避免这种情况的出现。
> 
> 谢谢，这个问题我明白了，我可以解决一下（因为 `alert` 吧）

昨日前端布局发生一点变动，重新生成的版本调整了一下导入导出按钮位置，做了一下防重复载入。请留意同步。

**Comment by Miller-du** [comment]
> 

之前的问题已解决；好的，谢谢

**Comment by Miller-du** [comment]
> > > > > > 您也可以看一下我之前发布的您的脚本，一直是同步更新的。地址：https://greasyfork.org/zh-CN/scripts/456901-chatgpt%E5%8A%9F%E8%83%BD%E5%A2%9E%E5%BC%BA 。（油猴不限制 Local Storage）
> > > > > 
> > > > > 
> > > > > 感谢搬运。稍后我将二位greasyfork的地址加入README。
> > > > > 顺便一提：oof标志符重载对于高负载时，登录页的“ChatGPT is at capacity right now” 提示应该也有作用， 建议将login页面也加入 @match 规则（不过可能需要延迟加载以防止某些问题？）。
> > > > 
> > > > 
> > > > 感谢。我设置的运行时刻是 `document-idie` ，是否还需要延迟？目前没有找到好的测试方法。
> > > 
> > > 
> > > 测试了一下，如@Haorwen所说，在cloudflare的token过期时，oof标志重载将会重写页面，有可能导致无法正常跳转。 不过，遇到这个问题的时候，重新刷新一下就好了。并不影响使用。 回头我让cgpt生成的时候，先检查一下oof标志再覆盖。应该可以避免这种情况的出现。
> > 
> > 
> > 谢谢，这个问题我明白了，我可以解决一下（因为 `alert` 吧）
> 
> 昨日前端布局发生一点变动，重新生成的版本调整了一下导入导出按钮位置，做了一下防重复载入。请留意同步。

之前的问题已解决，谢谢。好的。

**Comment by bigemon** [comment]
> 之前的问题已解决，谢谢。好的。

Hi,我留意到，您的仓库里的脚本，尚未同步到最近的版本。
(主要解决了CGPT最近更新前端导致的导出按钮消失)

在另外一个用户反馈的issues里。我已经给出了一个简单替换的结果，[一段临时的替换脚本](https://github.com/bigemon/ChatGPT-ToolBox/issues/14#issuecomment-1435448577)。
可以考虑在修改版本信息后，直接使用该脚本作为更新。

该替换已经进行了一些简单的测试，包含MacOS下的Safari与Chrome浏览器、UserScript 和TamperMonkey脚本管理器，
但并未在其它环境经过严谨的测试。
如果有其它环境下出现的兼容性问题，或是发现别的故障需要帮忙，欢迎反馈。

**Comment by bigemon** [comment]
在常见的系统和插件平台，暂时应该没有其它的不兼容现象了。
暂时Close
