### ISSUE TITLE
使用管理器“Userscripts”时出现问题

### ISSUE THREAD

**Issue by ChrisBDZ** [bigemon/ChatGPT-ToolBox#11]
当使用chatgpt-toolbox时，画面会闪烁：
https://user-images.githubusercontent.com/67193145/218125077-628bf3d2-5fa8-4d0a-836f-8fa7bbc7fb85.mp4

当使用ChatGPT功能增强时，网页会无响应：
https://user-images.githubusercontent.com/67193145/218125089-1901d18b-c616-480b-ba7e-a23e6ecfa5b6.mp4

**Comment by ChrisBDZ** [comment]
使用Tampermonkey时没有这个问题

**Comment by bigemon** [comment]
> 当使用chatgpt-toolbox时，画面会闪烁： https://user-images.githubusercontent.com/67193145/218125077-628bf3d2-5fa8-4d0a-836f-8fa7bbc7fb85.mp4
> 
> 当使用ChatGPT功能增强时，网页会无响应： https://user-images.githubusercontent.com/67193145/218125089-1901d18b-c616-480b-ba7e-a23e6ecfa5b6.mp4

感谢反馈，方便提供一下出问题时的系统信息吗？
例如：系统版本，设备类型(x86还是新款m系列芯片？)，以及safari的版本号和UserScript管理器版本。

此外，如果您知道如何编辑脚本，可以尝试一下[ 关于#10的讨论 ](https://github.com/bigemon/ChatGPT-ToolBox/issues/10#issuecomment-1427060601)里贴出的临时解决方案是否能够解决问题。

**Comment by ChrisBDZ** [comment]
谢谢你的关注。
我的系统版本：macOS 13.2 (22D49)
设备类型：x86 intel 10代i5
Safari浏览器版本：16.3 (18614.4.6.1.5)
管理器版本：4.3.3

**Comment by ChrisBDZ** [comment]
<img width="1552" alt="SCR-20230213-zo" src="https://user-images.githubusercontent.com/67193145/218324414-957a95bc-460a-4c7c-adda-3c07a888ddec.png">
这似乎并没有什么用。
<img width="1552" alt="SCR-20230213-zo" src="https://user-images.githubusercontent.com/67193145/218324433-c649b9bd-ba07-4669-8237-a4a2023cfd4a.png">

**Comment by bigemon** [comment]
> 这似乎并没有什么用。


感谢测试。
经过观察，这应该与开头的oof标志覆盖有关。
一个简单的修改应该可以解决这个问题，但由于目前openai的服务器未处于高负载状态，所以可能需要进行一些测试才会应用上去。
在此之前，您可以先尝试把旧的oof覆写相关的代码删除或者备注掉，
然后观察闪烁(不断重新载入)现象是否得到解决.

即,将旧的代码:

```
    // Get the entire page's source code as a string
    var pageSource = document.documentElement.outerHTML;

    // Replace '"oof":true' with '"oof":false'
    pageSource = pageSource.replace(/\"oof\":true/g, '"oof":false');

    // Replace the current page's source code with the modified version
    document.open();
    document.write(pageSource);
    document.close();
```

替换为备注屏蔽后的:
```
    // Get the entire page's source code as a string
    //var pageSource = document.documentElement.outerHTML;

    // Replace '"oof":true' with '"oof":false'
    //pageSource = pageSource.replace(/\"oof\":true/g, '"oof":false');

    // Replace the current page's source code with the modified version
    //document.open();
    //document.write(pageSource);
    //document.close();
```

或者直接删除。

**Comment by ChrisBDZ** [comment]
谢谢，替换后能够正常载入了。

**Comment by bigemon** [comment]
> 谢谢，替换后能够正常载入了。

如果方便的话，可以试试这个讨论帖里面最新给出的 [一个可能的修复方案](https://github.com/bigemon/ChatGPT-ToolBox/issues/10#issuecomment-1427060601) 是否可以正常工作。

**Comment by bigemon** [comment]
> 谢谢，替换后能够正常载入了。

已在新版本的小书签里修复，请等待其他平台的脚本仓库所有者同步即可。
