### ISSUE TITLE
2.17 没有导入会话选项了

### ISSUE THREAD

**Issue by httpservlet** [bigemon/ChatGPT-ToolBox#13]
![1676638368787](https://user-images.githubusercontent.com/4544749/219658230-e959294b-94ea-4e2b-a2d7-14bbc808576f.png)

**Comment by bigemon** [comment]
感谢反馈，稍后我会让CGPT重新生成

**Comment by bigemon** [comment]
已修

**Comment by httpservlet** [comment]
感谢老板的付出
