### ISSUE TITLE
脚本管理器一直重新加载问题

### ISSUE THREAD

**Issue by fangyuan99** [bigemon/ChatGPT-ToolBox#17]
https://github.com/lencx/ChatGPT
使用这个项目访问ChatGPT还是会出现重复加载的问题

**Comment by bigemon** [comment]
我不太理解你的意思。
这是一个第三方的CGPT客户端。并且它似乎并没有插件加载页面，也没有地址栏。

如果指的是右键查看元素（inspect element），然后在控制台里手动加载，通过这种方式进行使用。
那么在我本地的测试里，这可以正常工作。

<img width="800" alt="image" src="https://user-images.githubusercontent.com/3683548/221242898-23db9680-6f00-4d5b-b922-137f65956c96.png">
<img width="806" alt="image" src="https://user-images.githubusercontent.com/3683548/221243132-411ec7a6-b6a6-4452-ad40-5f404a6695dc.png">
<img width="793" alt="image" src="https://user-images.githubusercontent.com/3683548/221243320-4a43eae9-a4ec-4a51-a9d9-76573c9a05da.png">

**Comment by fangyuan99** [comment]
是我自己的问题，调整一下多脚本的加载顺序就好了
