### ISSUE TITLE
希望可以发布到tampermonkey下的几个脚本网址上

### ISSUE THREAD

**Issue by avcssef** [bigemon/ChatGPT-ToolBox#19]
我根据大佬的脚本，自己试用了一下，能正常运行并且在其他浏览器正常使用，这样子可以方便开启网址后直接运行

**Comment by bigemon** [comment]
欢迎搬运。
虽说我自己也会测一下，但由于精力有限，搬运后请尽量自行测试一些兼容性问题。
（例如万年出幺蛾子的safari+userscript）

**Comment by bigemon** [comment]
若需要更多帮助或者兼容性测试请再次打开此issue并且留言。
