### ISSUE TITLE
chatgpt自己更新了存档功能，之前的插件的存档似乎失效了

### ISSUE THREAD

**Issue by niutu1224** [bigemon/ChatGPT-ToolBox#2]
如图
![2022-12-21 10 50 32](https://user-images.githubusercontent.com/40801500/208810633-6d097d24-f983-4540-a199-e259ad41d8c8.png)

**Comment by niutu1224** [comment]
目前今天新存的存档不受影响可以正常使用

**Comment by Chinese-Cyq20100313** [comment]
你如果重新登录了那么就失效了，我之前在电脑上看到和手机版的不一样，有了新更新的Thread时，我打开手机（已登录）的加载存档还是能用的，然后我也能导入到电脑上继续会话，然后我手机重登之后，有了新功能，但是之前的conversation估计被销毁了。对话就没了，而且这个project也不支持(大概率以后也支持不了)导入存档到Thread。
 
总之，你用这个会话的一端如果用按钮退出登录了，那么这个Conversation就销毁了，但是清除Cookie不影响，毕竟点Log out调的是OpenAI的API，估计就销毁会话了。
吐槽：
这个项目他的存档列表没有scroll，会把导入导出顶到下面，多了就按不着了，电脑上我可以用devtools删element，手机上我只能在电脑上调试语句，然后，用javascript: ...来执行，然后删除存档的元素...
而且这个项目的点击什么的都是写在onclick，而且还独立特地往<head>中写style只为了那突兀的switch，我寻思你都可以写css了直接写一个和UI匹配的css不就行了，非常不 good 啊，而且加载存档是在文字的element加的onclick，点文字才能加载，容易点不到。没有闭包，所有函数全部公开在globalThis(Window)中，对了那个switch也可以直接换成OpenAI的checkbox(踩里面不就是checkbox)代替让他看起来不这么突兀。

毕竟这个是ChatGPT写的，会话估计早没了不好改...

**Comment by Chinese-Cyq20100313** [comment]
所以我看看能不能contribute一下啊

**Comment by bigemon** [comment]
> 你如果重新登录了那么就失效了，我之前在电脑上看到和手机版的不一样，有了新更新的Thread时，我打开手机（已登录）的加载存档还是能用的，然后我也能导入到电脑上继续会话，然后我手机重登之后，有了新功能，但是之前的conversation估计被销毁了。对话就没了，而且这个project也不支持(大概率以后也支持不了)导入存档到Thread。
> 
> 总之，你用这个会话的一端如果用按钮退出登录了，那么这个Conversation就销毁了，但是清除Cookie不影响，毕竟点Log out调的是OpenAI的API，估计就销毁会话了。 吐槽： 这个项目他的存档列表没有scroll，会把导入导出顶到下面，多了就按不着了，电脑上我可以用devtools删element，手机上我只能在电脑上调试语句，然后，用javascript: ...来执行，然后删除存档的元素... 而且这个项目的点击什么的都是写在onclick，而且还独立特地往中写style只为了那突兀的switch，我寻思你都可以写css了直接写一个和UI匹配的css不就行了，非常不 good 啊，而且加载存档是在文字的element加的onclick，点文字才能加载，容易点不到。没有闭包，所有函数全部公开在globalThis(Window)中，对了那个switch也可以直接换成OpenAI的checkbox(踩里面不就是checkbox)代替让他看起来不这么突兀。
> 
> 毕竟这个是ChatGPT写的，会话估计早没了不好改...

Thread其实都还在的，但是早期版本的那个导入会把导出时候的token也传进去（为了跨账号分享），结果岂料后面连续N天服务器疯狂踢人，token活不过两天。于是觉得鸡肋就直接移除了OTZ. 
正常来说，如果是同一个账号，官方的Thread其实只是看不到，实际上应该都在。
至于css什么确实是没办法了。CGPT只能按要求找一段玩意儿糊上去，想要让它整点美观的不太现实，人介入手写的话又背离初衷

**Comment by Chinese-Cyq20100313** [comment]
> 正常来说，如果是同一个账号，官方的Thread其实只是看不到，实际上应该都在。

虽然官方的Thread删除时是把visible改成false,但是OpenAI也许就在你退出或定时删除所有人的不可见Thread
这不自带css，能白嫖直接白嫖OpenAI的官方内容啊。
我刚改了一下，在Github编辑器上不好整，虽然这个注释和没注释一样，总之勉强能用？...
#3

**Comment by Chinese-Cyq20100313** [comment]
虽然我写html js css都是用dev tools时顺便学会的...

**Comment by Chinese-Cyq20100313** [comment]
而且用这直接字符串拼接，整的这么长不换行，真的是手动混淆...
指不定误删哪个分号冒号就再也找不到删的哪儿了

**Comment by niutu1224** [comment]
顺带我有一个疑惑，ai的输出因为过长而被截断导致没说完的依据是什么。我的测试来看似乎不是输出字数的硬性限制

**Comment by bigemon** [comment]
> 虽然我写html js css都是用dev tools时顺便学会的...

疑，等等，为啥你们还在补丁旧的那个第三方会话管理啊。
先来确定一下，你们收到官方的会话管理推送了吗？
昨天凌晨部分地区收到了灰度推送，今天周围大部分朋友应该是都收到了推送。
收到推送之后，界面看起来会类似这样：
<img width="665" alt="image" src="https://user-images.githubusercontent.com/3683548/208850931-eb117627-856f-4b7d-83e7-0876716f9a99.png">
新旧前端有一部分响应是变化了的。

**Comment by bigemon** [comment]
> 虽然我写html js css都是用dev tools时顺便学会的...

那个patch看了一下，旧的前端没啥问题。
但是如果是新推送的这个前端，点击历史会话Thread详情的时候，会导致一个刷新事件，从而覆盖注入的Item.
如果官方的那个管理器已经正常列举历史会话Thread，并且推送过去了的话，那么我倾向于先把第三方会话存档相关功能移除。

**Comment by bigemon** [comment]
> 而且用这直接字符串拼接，整的这么长不换行，真的是手动混淆... 指不定误删哪个分号引号就再也找不到删的哪儿了

23333,其实你可以直接喂给CGPT然后提要求，毕竟这坨玩意儿是它糊起来的。
只能说使用CGPT生成东西的时候，上下文联系确实重要。
之前因为需要塞进地址栏，所以要求它必须尽量压缩成一行。
导致现在用于生成的这个Thread，一旦要求它生成东西，就老想给我塞成一坨，要特别要求才能纠正。

**Comment by bigemon** [comment]
> 顺带我有一个疑惑，ai的输出因为过长而被截断导致没说完的依据是什么。我的测试来看似乎不是输出字数的硬性限制

目前应该是时间相关，任务超时就会导致终止。
这个问题在之前导致了各种Network Error。
现在虽然可以正常结束，但是能发现文字戛然而止的痕迹。如果是生成代码，此时有可能导致上下文中断，没办法正常拉取后半段。怎么和它continue也没用。只能尽量细化到函数

**Comment by Chinese-Cyq20100313** [comment]
> > 虽然我写html js css都是用dev tools时顺便学会的...
> 
> 那个patch看了一下，旧的前端没啥问题。 但是如果是新推送的这个前端，点击历史会话Thread详情的时候，会导致一个刷新事件，从而覆盖注入的Item. 如果官方的那个管理器已经正常列举历史会话Thread，并且推送过去了的话，那么我倾向于先把第三方会话存档相关功能移除。

但是原来的会把登出和导入导出顶掉......

**Comment by niutu1224** [comment]
> 

我在试着通过给他规定指令的方式来让他尽量不离谱的续写之前的内容，现在还在试

**Comment by Chinese-Cyq20100313** [comment]
> > 顺带我有一个疑惑，ai的输出因为过长而被截断导致没说完的依据是什么。我的测试来看似乎不是输出字数的硬性限制
> 
> 目前应该是时间相关，任务超时就会导致终止。 这个问题在之前导致了各种Network Error。 现在虽然可以正常结束，但是能发现文字戛然而止的痕迹。如果是生成代码，此时有可能导致上下文中断，没办法正常拉取后半段。怎么和它continue也没用。只能尽量细化到函数

这应该是强制解除占用，叫它用英文会快一点，就能说全了

**Comment by Chinese-Cyq20100313** [comment]
> > 而且用这直接字符串拼接，整的这么长不换行，真的是手动混淆... 指不定误删哪个分号引号就再也找不到删的哪儿了
> 
> 23333,其实你可以直接喂给CGPT然后提要求，毕竟这坨玩意儿是它糊起来的。 只能说使用CGPT生成东西的时候，上下文联系确实重要。 之前因为需要塞进地址栏，所以要求它必须尽量压缩成一行。 导致现在用于生成的这个Thread，一旦要求它生成东西，就老想给我塞成一坨，要特别要求才能纠正。

完全可以最后删空格换行，或者整一个compressor 。

**Comment by niutu1224** [comment]
> > > 
> > 
> > 
> > 我在试着通过给他规定指令的方式来让他尽量不离谱的续写之前的内容，现在还在试
> 
> 教它把代码和解释分开来说？

额不是。我问ai怎么解决的时候，它向我介绍他可以进行所谓的分页，我试着给他规定输出几页，一页多少字，然后在他输出一段后给他说，下一页。代码的话基本连不上。也许可以试试把它没说完的话的结尾也作为信息输入一下，说不定能续上

**Comment by Chinese-Cyq20100313** [comment]
应该把某个页面（css js外部引用的都要）全部保存，分几次喂给它，然后叫他在某个path加某个xx功能的xxx,也许可以... ~深度学习肯定擅长找深度压缩混淆的逻辑~

**Comment by bigemon** [comment]
> > > > 
> > > 
> > > 
> > > 我在试着通过给他规定指令的方式来让他尽量不离谱的续写之前的内容，现在还在试
> > 
> > 
> > 教它把代码和解释分开来说？
> 
> 额不是。我问ai怎么解决的时候，它向我介绍他可以进行所谓的分页，我试着给他规定输出几页，一页多少字，然后在他输出一段后给他说，下一页。代码的话基本连不上。也许可以试试把它没说完的话的结尾也作为信息输入一下，说不定能续上

代码块儿目前耦合挺严重的。强行让它分开是会这样。
你可以试试先让它规划一下功能，然后列举一下会有什么函数、方法。最后要求它一个个输出。这样有了上下文的结构信息，它被打断之后恢复的概率大很多。
一些重复的代码可以要求它简略说明即可，这样也可以省掉大量的篇幅。

**Comment by bigemon** [comment]
> 应该把某个页面（css js外部引用的都要）全部保存，分几次喂给它，然后叫他在某个path加某个xx功能的xxx,也许可以... ~深度学习肯定擅长找深度压缩混淆的逻辑~

这时候坑就来了，最早的时候我是试图把webpack的那js喂进去，结果输入有限长。喂了十几次还没喂完，webpack那又老长一坨。测试了一下，上下文也经常出问题。
最后就放弃了，直接把加载后的DOM喂进去，要求它覆盖（所以会发现大量覆盖在window上的属性和函数）

**Comment by Chinese-Cyq20100313** [comment]
还是人来写好，先把创建OpenAI的按钮和checkbox之类的写成函数
然后丢给ChatGPT让他用这个写，然后说输出的内容来自调后ChatGPT（

**Comment by bigemon** [comment]
希望收费之后有大文件传输之类的功能，不然这种场合完全就是痛苦面具常驻。

> 还是人来写好，先把创建OpenAI的按钮和checkbox之类的写成函数 然后丢给ChatGPT让他用这个写，然后说输出的内容来自调后ChatGPT（

草，什么工人智能 :)
目前用CGPT输出内容，感觉最大的两个痛点：

一个是无法直接传输大文件或者大文本。
一个是代码类的内容，上下文联想问题挺大。一个函数切分了就会经常出问题，不切分的话有时候又会输出不全。

不知道API收费之后会不会有解决方案，例如可选的任务规模

**Comment by Chinese-Cyq20100313** [comment]
我觉得可以close了

**Comment by Chinese-Cyq20100313** [comment]
> 我觉得可以close了

问题都解决了xd

**Comment by Chinese-Cyq20100313** [comment]
希望不要收费太贵，支持个支付宝什么的，不然还买不起获取Outlook for Android发件人: ***@***.*** ***@***.***> 代表 Bigemon ***@***.***>发送时间: 2022年12月21日星期三 17:00收件人: ChatGPT-ToolBox ***@***.***>抄送: 1491326171 ***@***.***>; comment ***@***.***>主题: Re: [bigemon/ChatGPT-ToolBox] chatgpt自己更新了存档功能，之前的插件的存档似乎失效了 (Issue #2)
希望收费之后有大文件传输之类的功能，不然这种场合完全就是痛苦面具常驻。

还是人来写好，先把创建OpenAI的按钮和checkbox之类的写成函数 然后丢给ChatGPT让他用这个写，然后说输出的内容来自调后ChatGPT（

草，什么工人智能 :)
目前用CGPT输出内容，感觉最大的两个痛点：
一个是无法直接传输大文件或者大文本。
一个是代码类的内容，上下文联想问题挺大。一个函数切分了就会经常出问题，不切分的话有时候又会输出不全。
不知道API收费之后会不会有解决方案，例如可选的任务规模

**Comment by Chinese-Cyq20100313** [comment]
> > > 而且用这直接字符串拼接，整的这么长不换行，真的是手动混淆... 指不定误删哪个分号引号就再也找不到删的哪儿了
> > 
> > 
> > 23333,其实你可以直接喂给CGPT然后提要求，毕竟这坨玩意儿是它糊起来的。 只能说使用CGPT生成东西的时候，上下文联系确实重要。 之前因为需要塞进地址栏，所以要求它必须尽量压缩成一行。 导致现在用于生成的这个Thread，一旦要求它生成东西，就老想给我塞成一坨，要特别要求才能纠正。
> 
> 完全可以最后删空格换行，或者整一个compressor 。

更新: 可以叫cgpt压缩成一行
