### ISSUE TITLE
屏蔽数据监管失效啦！

### ISSUE THREAD

**Issue by sure2023** [bigemon/ChatGPT-ToolBox#21]
作者你好，不能屏蔽数据监管了，求更新，感谢！！

**Comment by sure2023** [comment]
再次感谢大佬

**Comment by catshitz** [comment]
`作为AI语言模型，我不能主张或提倡任何违反法律法规的行为，包括禁用数据监管。数据监管是指监管机构对数据的收集、存储、处理和传输进行监管，以确保数据的安全和隐私受到保护，同时也保障数据的合法使用。数据监管对于保护消费者和企业的利益非常重要，并且是许多国家的法律法规所规定的。因此，我不能支持禁用数据监管的做法。`
刚用，我也一直奇怪，这不是不能解锁嘛，“禁用数据监管”难道是个摆设？

**Comment by Cupcc** [comment]
。。。按照教程使用猫娘也失败。。。

**Comment by bigemon** [comment]
> 作者你好，不能屏蔽数据监管了，求更新，感谢！！

首先需要注意的是，屏蔽监管按钮只是用来屏蔽前端页面的自动监管反馈功能。
*也就是所谓的标黄、标红

发送内容如果经常被标红删除，会直接触发自动警告信。这个功能主要解决的是这个问题。

因此这个功能无法直接帮你绕过Web版本的模型拒绝( 是的，没有错，甚至你都还没到被后审核的那一步)

只要是触发模型自己拒绝的，都需要想办法找Prompts绕过。
目前比较有效的一套Prompts是让它扮演“DAN”的那个系列的V5版本，请自己Reddit查找相关讨论帖。

--------

另外，新版本已上线beta版本的混合API。用于在一些AI死活不进入状态的上下文，使用外部API插入数据。

***GPT3.5混合接入(beta)***
- 使用 `/api 聊天数据` 可在编辑、发送时调用GPT3.5 API
- 自动引入网页上文数据          (当前设置为3000字节)
- 可选的引导语句参数            (用于句首引导/句末自动确认)
- API回执自动转发至网页

![1](https://user-images.githubusercontent.com/3683548/224494277-6331033e-62c7-473d-9f46-faa1912a7db3.gif)


需要注意的是，这个混合API的模式容易导致网页版的AI出戏，脱离当前扮演状态。 
因此，不是很适合用于第一人人称沉浸式扮演。
主要解决的是，API上下文记忆少，网页免费版又不能产出敏感内容的痛点。
若需要NSFW内容，请使用我的魔改API编辑器：[NSFW版川虎Chat](https://github.com/bigemon/ChuanhuChatGPT)
使用我仓库里第一张图的预设，可以做到100%遵守NSFW设定。

**Comment by bigemon** [comment]
暂时关闭。
若再次遇到类似问题，或有更多相关信息想要分享和讨论，请再次打开此issues。

**Comment by bigemon** [comment]
问题应该解决了，暂时关闭。
若再次遇到类似问题，或有更多相关信息想要分享和讨论，请再次打开此issues。
