### ISSUE TITLE
开启插件后，闪一下就白屏。

### ISSUE THREAD

**Issue by Cupcc** [bigemon/ChatGPT-ToolBox#22]
## 系统信息
系统：MacOS Monterey 12.6.1
浏览器：Chrome 版本 110.0.5481.177（正式版本） (x86_64)
## 问题描述
刷新之后，闪一下chat的侧边栏然后就白屏。 若关闭插件，就正常。  
<img width="1258" alt="image" src="https://user-images.githubusercontent.com/53716543/223695798-744f9dc3-9ffa-46e6-a01d-c5a30034d942.png">

已经尝试，重启，重试，重新打开tab标签页，或重新打开插件，有时候能成功载入，但大多数时候无效。。

**Comment by bigemon** [comment]
暂时推断依然是oof标志重载时，页面还没渲染完成。

可能的问题原因:

1. 这个重载是用来解决高负载时，无法登录 与 '重新生成' 按钮被禁用的问题。
2. oof标志符被写死在页面。只能通过覆盖后重载本页实现。
3. 最近官方负载很高，页面好卡。脚本重加载时可能刚好打断了这个进程，导致空白页面。

鉴于官方前端多次修改,且有较长一段时间没观察到这个问题，暂时已在新版脚本里将/chat聊天页面排除在oof重载的清单里。
可以留意一下新版本的状况。

**Comment by bigemon** [comment]
在新版本的Chrome小书签里，已临时修正此问题。
若使用的是第三方仓库添加的Userscript，请联系仓库作者更新脚本并测试兼容性。
若有更多相关问题，请再次打开此issues
