### ISSUE TITLE
因为使用了api调用gpt3.5功能而被封号

### ISSUE THREAD

**Issue by RainEndyumo** [bigemon/ChatGPT-ToolBox#24]
建议谨慎使用

**Comment by bigemon** [comment]
这并非针对插件用户，而是由于所在IP或注册时的账号批次满足了API滥用(薅羊毛)标准。
最近OpenAI正在严打滥用API行为，主要针对的是某些批量注册并薅免费额度的群体。

由于部分不在服务区的用户 ，在注册、登录、激活邮箱、日常使用时，IP往往是不同的地域(挂了梯子)，则可能会因此受到误伤。
如果确信自己不是Taobao或是其它平台买的批量注册号。可以尝试发邮件申诉。

总体而言，使用API时确保没有以下状况，
若满足以下一条或多条高危条件，则建议改用付费KEY或者小号的APIKey：

1.  调用OpenAI的服务或是API时，使用公共代理服务 ( 几百人都在用那种 )
2.  消耗的是免费3.5API额度。并且在公共平台，使用同一个IP，与其它免费APIKey同时期发出了大量的请求
3.  注册IP归属地、激活邮件IP归属地、绑定手机号的归属地、常用登录IP归属地，以上归属地出现两个以上地理位置很远的地区。
4. Chrome未关闭Quic协议，并且代理未开启全局，导致从UDP泄露当前所在地


具体相关详情建议去Reddit查看相关讨论帖。
昨日Ban了巨量账号，海量不使用任何插件的付费用户也受到波及。确信自己不属于滥用薅羊毛的范畴可以尝试发邮件申诉。

**Comment by bigemon** [comment]
已添加本讨论帖链接和相关警告信息至ReadMe。
若有更多分享信息请再次打开此issues。
