### ISSUE TITLE
今天发现好像防止删除功能失效了

### ISSUE THREAD

**Issue by gothist** [bigemon/ChatGPT-ToolBox#26]

**Comment by bigemon** [comment]
请问是UI加载/附加不上去。还是防删失效？
macos + chrome刚才测试防删应该还是正常工作的。
如果只是UI加载有问题可以试着拖动一下窗口边框大小，应该会正常触发后加载UI

**Comment by bigemon** [comment]
请问是UI加载/附加不上去。还是防删失效？
macos + chrome刚才测试防删应该还是正常工作的。
如果只是UI加载有问题可以试着拖动一下窗口边框大小，应该会正常触发后加载UI

**Comment by gothist** [comment]
我试试吧，单纯UI有问题也会导致换了个浏览器登录仍然刷不出来内容的问题么？ 而且有好几次我是能看见有字打出来然后又消失了 最后对话框是空的 并且换了浏览器也没有内容的情况

**Comment by gothist** [comment]
顺带我是plus会员用的是3.5非API对话会有影响么？

**Comment by bigemon** [comment]
> 顺带我是plus会员用的是3.5非API对话会有影响么？

应该是无影响。测试是在我的2个账号进行，涵盖了plus、普通会员、GPT4敏感数据等。

我认为可能和浏览器环境有关系，如果方便的话，可以提供更多信息吗？

例如： 
浏览器环境（chrome/edge/safari） 
系统类型(windows/mac/linux等)  
CPU类型(Apple SIlicon / x86_64 / arm64) 
使用方式: (插件、chrome小书签 )

需要注意的是，脚本方式的仓库现在是第三方作者在做搬运后的兼容性测试和维护。如果发生了问题，建议先使用chrome书签的方式使用，看看能否复现。

**Comment by gothist** [comment]
我刚刚又试了一下不是插件的问题，好像是我让他输出文本的特定格式，让他把内容隐藏了，抱歉耽误你时间了。“   [GM]：”开头的文本都会被隐藏 我不太懂代码 总之抱歉。
