### ISSUE TITLE
浏览器书签执行后页面没变化

### ISSUE THREAD

**Issue by Sherlock-Holo** [bigemon/ChatGPT-ToolBox#29]
正常是会有一个小弹窗提示版本的嘛
4月3号这个小弹窗没有了

**Comment by bigemon** [comment]
一般而言这是代理或者网络因素导致的。
为了提高部分github受干扰地区的访问速度，脚本使用了ghproxy.com作为cdn缓存。
如果在线加载的版本无法正常工作，
请检查以下链接是否可以正常访问:
[CDN缓存地址](https://ghproxy.com/https://raw.githubusercontent.com/bigemon/ChatGPT-ToolBox/main/toolbox-chrome-bookmark.js)
[仓库地址](https://raw.githubusercontent.com/bigemon/ChatGPT-ToolBox/main/toolbox-chrome-bookmark.js)

- 如果 CDN缓存地址 无法联通，但仓库地址可以访问。请改用以下小书签

```
javascript:var xhr=new XMLHttpRequest();xhr.open('GET','https://raw.githubusercontent.com/bigemon/ChatGPT-ToolBox/main/toolbox-chrome-bookmark.js',true);xhr.onload=function(){if(xhr.readyState===4&&xhr.status===200){eval(xhr.responseText)}};xhr.send(null);
```

- 如果两个地址均无法访问。
请检查代理和网络，或者将 ghproxy.com 以及 raw.githubusercontent.com 域名加入代理名单。
又或者，考虑直接使用完整版本脚本（使用完整脚本需要手动更新）

**Comment by jasonlau222** [comment]
还是不行哦。哪里的问题呢？

**Comment by bigemon** [comment]
ghproxy近日因不明原因，在大陆被严重阻断
现已更新相关小书签的镜像指向。

Chrome小书签用户改用以下动态拉取书签:
```
javascript:var xhr=new XMLHttpRequest();xhr.open('GET','https://raw.gitmirror.com/bigemon/ChatGPT-ToolBox/main/toolbox-chrome-bookmark.js',true);xhr.onload=function(){if(xhr.readyState===4&&xhr.status===200){eval(xhr.responseText)}};xhr.send(null);
```

脚本管理器用户请使用以下链接安装镜像后的脚本:

🔗[镜像-中国大陆](https://raw.gitmirror.com/bigemon/ChatGPT-ToolBox/main/toolbox.user.js)
