### ISSUE TITLE
禁用数据监管按扭偏移

### ISSUE THREAD

**Issue by RoyRao2333** [bigemon/ChatGPT-ToolBox#31]
如图：

<img width="1800" alt="image" src="https://user-images.githubusercontent.com/31413093/230536570-22f1675a-4898-49d4-b119-aeeb23cf5421.png">

系统：macOS 13.3
浏览器：Firefox Developer Edition 112.0b9 (64-bit)
油猴：4.18.1

**Comment by bigemon** [comment]
此问题已发现并且在4月6日更新的最新版本修复。
但脚本管理器需要等第三方仓库作者适配。

稍后我会上传一个在safari/chrome + macos + TamperMonkey测试通过的版本到仓库。
但在Firefox下有可能会有一些没测试到的小问题。

**Comment by bigemon** [comment]
已更新至ReadMe:

🔗[镜像-中国大陆](https://raw.gitmirror.com/bigemon/ChatGPT-ToolBox/main/toolbox.user.js)

🔗[海外-Github直链](https://raw.githubusercontent.com/bigemon/ChatGPT-ToolBox/main/toolbox.user.js)

⚠️以上脚本仅在以下环境测试通过:
- MacOS/Windows + Chrome + Tampermonkey 
- MacOS + Safari + Userscript

由于精力有限，无法保证在其它环境下的兼容性。此外，由于网络封锁，大陆地区用户拉取时，可能会受到阻断。
若发现问题请在此issues下反馈。

**Comment by RoyRao2333** [comment]
实测最新版完美修复，感谢老哥 🎉
