### ISSUE TITLE
waf bypass 失效

### ISSUE THREAD

**Issue by itsuki-1** [bigemon/ChatGPT-ToolBox#36]
輸入waf key後仍然無法bypass access denied 問題
![Jzud8AR](https://user-images.githubusercontent.com/118049799/232208715-c40348d8-9d4c-4edf-894f-c35b72e06690.png)
![iU36BKO](https://user-images.githubusercontent.com/118049799/232208723-f9eb172a-5706-4732-a688-7a6a03547a79.png)

**Comment by bigemon** [comment]
4月16日凌晨1时起，该方案已失效。同时有部分小机房的网段被加入黑名单。
于此同时，WARP分流方案暂时不受影响。

**Comment by 631068264** [comment]
@itsuki-1 WAF key 是什么东西？怎么来的 ？遇到一样的问题。

@bigemon 这种情况是我号被封了？

**Comment by bigemon** [comment]
WAF相关的特权在部分地区短暂的放松后又一次的收紧,
目前已正式移除该功能.
