### ISSUE TITLE
绕入页面后无法回车发消息？同时偶尔会遇到WAF问题

### ISSUE THREAD

**Issue by parseva1** [bigemon/ChatGPT-ToolBox#37]

**Comment by bigemon** [comment]
你好，请提供一些更详细的信息，例如:
是否使用最新的脚本，使用平台(移动端/PC/MAC)和浏览器（Chrome/edge/safari）。
在什么场景下无法回车发消息，是发出去了但是报错了？
还是回车功能失效，必须手动点击按钮才能发送？

**Comment by bigemon** [comment]
超过2周没有回应,暂时关闭此issues,
若有其它更新的信息,请重新打开即可.
