### ISSUE TITLE
Safari+Tampermonkey导致网页四周闪烁绿色

### ISSUE THREAD

**Issue by ChrisBDZ** [bigemon/ChatGPT-ToolBox#39]
<img width="1552" alt="235354747-6efb67e0-8945-41eb-93d9-185be32d098c" src="https://user-images.githubusercontent.com/67193145/235354825-9bcad8af-787b-4319-b899-11f96d1c523e.png">
如图

**Comment by Chinese-Cyq20100313** [comment]
建议保存网页，发整个html

**Comment by bigemon** [comment]
> <img alt="235354747-6efb67e0-8945-41eb-93d9-185be32d098c" width="1552" src="https://user-images.githubusercontent.com/67193145/235354825-9bcad8af-787b-4319-b899-11f96d1c523e.png">
> 
> 如图

你好 , 这是连接心跳指示器.

原因:

最近的版本里加入了连接维持功能. 用于帮助没开通plus的免费用户维持连接,从而避免频繁刷新页面,
之前应该有不少用户遇到过,输入了一堆东西,一回车后红字报错, 这其实就是和Cloudflare的连接断开需要刷新. 

从原理上来说,我们需要再后台10秒进行一次连接维持动作. 
因此,需要有一个指示器简单的表示当前是否是连接状态.
目前是简单做了个光效,
绿色呼吸效果是正常连接,
红色常亮+ 右上角连接断开则表示连已断开,无法正常发送.


鉴于从4月27日开始,官方已经恢复了plus会员的WAF穿透 ( 尽管IP封禁不再提供豁免 ) , 后续版本我们可能会考虑提供一个按钮,用来切换这个连接维持功能的状态.
又或者,可以通过判断是否是plus会员,从而自动启用/关闭这个功能.

**Comment by ChrisBDZ** [comment]
谢谢
