### ISSUE TITLE
关于最新引入的连接维持的新特性

### ISSUE THREAD

**Issue by Magicen0722** [bigemon/ChatGPT-ToolBox#44]
它会在整个对话框体中持续闪烁绿光或许会损害观感？或许可以改变成类似网页右上角一个显示状态的灯？类似红绿黄？我不不清楚是这个库的原因还是这个插件的原因。
![企业微信截图_16831890169162](https://user-images.githubusercontent.com/66616125/236151537-c18494eb-7604-4b84-adba-bb0982041004.png)
插件连接：`https://greasyfork.org/zh-CN/scripts/456901-chatgpt%E5%8A%9F%E8%83%BD%E5%A2%9E%E5%BC%BA`
感谢任何形式的帮助！

**Comment by bigemon** [comment]
这个连接指示特效确实是最近新增的功能引入的.
鉴于最近确实收到了一些相关困扰的反馈,
或许我们可以考虑加入一个开关,  只在链接已断开(这种情况下无法正常对话) 时提供一个红色的提示. 
或是,如您所说,: 干脆更改一个样式.

最近事情有点多,等我腾出手了,下个修订版本会处理一下这个问题.

**Comment by Magicen0722** [comment]
> 这个连接指示特效确实是最近新增的功能引入的. 鉴于最近确实收到了一些相关困扰的反馈, 或许我们可以考虑加入一个开关, 只在链接已断开(这种情况下无法正常对话) 时提供一个红色的提示. 或是,如您所说,: 干脆更改一个样式.
> 
> 最近事情有点多,等我腾出手了,下个修订版本会处理一下这个问题.


好的谢谢~这个功能确实帮我解决了很多时候需要重复刷新的问题，谢谢你的工作！
