### ISSUE TITLE
添加CSS stylesheet 无效

### ISSUE THREAD

**Issue by Chinese-Cyq20100313** [bigemon/ChatGPT-ToolBox#53]
之前注释掉了所有添加内容，所以那一整个函数都没用了，可以都删掉，之前忘了删了

**Comment by bigemon** [comment]
先留着吧。如果回头没有什么外部样式需要添加，下个版本一块儿移除掉。

官方最近开始爆产能堆功能了，比如正在灰度推送的「会话分享」功能。

功能可能要调整一下。

**Comment by bigemon** [comment]
已移除
