### ISSUE TITLE
建议：按钮点击使用addEventListener('click', function(){})处理

### ISSUE THREAD

**Issue by Chinese-Cyq20100313** [bigemon/ChatGPT-ToolBox#6]

**Comment by bigemon** [comment]
通过强制指明实现点击的方法，可以简单的重生成使用addEventListener的版本。
不过由于在当前使用的这个chatGPT会话上下文里，它倾向于使用onclick，
而由于官方的限制，每次要求它重生成都需要拼接好几段生成结果。
所以大多数时候我并不会特意要求chatGPT遵循某种代码规范。



PS：这种奇怪的代码生成风格的成因其实有点绕，我下面会尽量解释一下这背后可能发生了什么。

官方前端JS中, nav的一些元素的自适应响应受到webpack打包的一个巨无霸js控制。
nav在页面宽度发生变化，或者移动端的情形下,这部分元素会发生改变甚至被移除，
因此，**我们需要定期重新附加相关点击事件，以保持对nav的覆盖**。

最理想的情况下，我们可以通过简单的hook或者修改这部分代码直接达成目的。
但由于以下原因不能这么做：

1. chatGPT的输入有隐性长度限制。过长的代码段将会被截断并且没有任何通知，因此每次只能喂一部分代码。而最近加入的每小时频率限制更是使得这个状况雪上加霜。
2. 官方前端打包的webpack的js非常的长，多次强行截断会导致chatGPT在理解上下文的时候出现严重错误。
3. 这个webpack的js经常进行更改，对它进行修改必须搭配对/chat页面的重写，否则可能导致一系列问题

由于以上3点原因，目前的工作流在人类不过多介入的情况下，只能向chatGPT喂入dom属性和innerHTML，然后再向它提需求。
ChatGPT基本处于一个半黑盒状态，只能通过描述了解状况并且尝试提供解决方案。


在无法了解webpack的前端代码的情况下，它很自然的选择了在window.onresize里处理事件重附加，并且重新覆盖移动端的sidebar按钮事件。
但这种选择如果遇上了addEventListener，就会对它造成一些困扰：

1. chatGPT缺乏这个元素里其它EventListener的信息，而这部分又处于webpack打包压缩的js里，没法直接灌给它。
2. window.onresize 可能被重复触发，所以chatGPT必须假设里面的代码会被重复运行并且进行处理。
3. EventListener可以同时存在多个。为了不重复添加事件响应，如果要使用addEventListener，它就必须为所有元素增加一个flag，用来表示已patched.并且在addEventListener之前判断元素的flag。

显然，如果使用onclick，就不需要额外进行任何处理，chatGPT只需要无脑的赋值这个事件属性即可。
对于它而言，这是一个比较稳妥并且简单粗暴的方案。
因此，如果不在任务描述里强制要求使用addEventListener，在我当前构建的会话上下文里，chatGPT几乎总是优先使用onclick。  （摊手
