### ISSUE TITLE
开启脚本后跳too many request in 1 hour, 刷新不打开脚本又可以正常使用，请问大家使用时正常吗？

### ISSUE THREAD

**Issue by kemononoke** [bigemon/ChatGPT-ToolBox#8]

**Comment by erictamhk** [comment]
too many request in 1 hour, 可以正常使用?!

**Comment by kemononoke** [comment]
> too many request in 1 hour, 可以正常使用?!

不打开插件的时候不会跳出 too many request in 1 hour, 可以正常使用

**Comment by kemononoke** [comment]
好像是因为我忘记关chatwaifu了..
