### ISSUE TITLE
功能建议：不限制文本输出长度

### ISSUE THREAD

**Issue by ECR-Lite** [bigemon/ChatGPT-ToolBox#9]
希望可以添加文本不限制长度输出的功能

**Comment by Haorwen** [comment]
这个功能不是浏览器端的，无法实现

**Comment by bigemon** [comment]
> 希望可以添加文本不限制长度输出的功能

关于这点，目前版本的免费公开测试的api似乎是无法实现的。
通过抓包可以观察到：

1.用户输入有隐性的截断，即便通过解除前端限制输入了超长文本，也会在api那儿截断。
2.返回的数据中，[done] 信号由后端api发送且主动断开。

基于这两点，在当前公开测试版本的api里，修改前端的限制没有实际意义。

如果是期望在文学创作中让cgpt接着写，可以在截断位置回复它 ”接着写“、”请继续说“ 等字词。
因此，我们应该可以添加一个自动回复实现类似的功能。但介于目前严苛的每小时请求数量限制，我觉得可能不是一个好主意。

**Comment by bigemon** [comment]
鉴于暂时没有好的方式实现该特性，先将它Close。
若有其它思路欢迎讨论。
